apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://api.k8s-${project}-${environment}.internal:8080
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: kubelet
    name: kubelet-to-kubernetes
current-context: kubelet-to-kubernetes
users:
  - name: kubelet
