autoDiscovery:
  clusterName: ${cluster_name}

awsRegion: ${aws_region}

cloudProvider: aws

# K8S | CA
# 1.12.X | 1.12.X
# 1.11.X | 1.3.X
# 1.10.X | 1.2.X
image:
  tag: v1.2.3

# https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca
extraArgs:
  v: 4
  stderrthreshold: info
  logtostderr: true
  # write-status-configmap: true
  # leader-elect: true
  # expander: least-waste
  # balance-similar-node-groups: true
  # min-replica-count: 2
  # max-node-provision-time: 15m0s
  # scan-interval: 10s
  # scale-down-enabled: true
  # scale-down-delay: 10m
  # scale-down-non-empty-candidates-count: 5
  # scale-down-unneeded-time: 10m
  scale-down-utilization-threshold: ${utilization_threshold}
  # skip-nodes-with-local-storage: false
  # skip-nodes-with-system-pods: true

podAnnotations:
  iam.amazonaws.com/role: ${autoscaler_role_arn}
replicaCount: 1

rbac:
  create: true
  pspEnabled: true

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

affinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: Exists
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists
