---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${cluster-name}
  name: ${name}
spec:
  image: kope.io/${kubernetes_ami}
  machineType: ${instance_type}
  maxSize: ${max}
  minSize: ${min}
  role: Node
  subnets:
${subnets}
  cloudLabels:
    role: worker
    subnet: app
    access: private