---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${cluster-name}
  name: ${name}
spec:
  image: 496014204152/${kubernetes_ami}
  machineType: ${instance_type}
  maxSize: ${max}
  minSize: ${min}
  ${spot_price}
  role: Node
  ${extra_worker_securitygroups}
  subnets:
${subnets}
  cloudLabels:
    role: worker
    subnet: app
    access: private
  additionalUserData:
  - name: teleport.sh
    type: text/x-shellscript
    content: |
      ${teleport_bootstrap}
  - name: teleport.txt
    type: text/cloud-config
    content: |
      write_files:
      ${teleport_config}
      ${teleport_service}
