---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: ${name}
spec:
  api:
    loadBalancer:
      type: ${elb_type}
      idleTimeoutSeconds: 300
  channel: stable
  cloudProvider: aws
  configBase: s3://${k8s_data_bucket}/${name}
  etcdClusters:
  - etcdMembers:
${etcd_members_main}
    name: main
  - etcdMembers:
${etcd_members_events}
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubeAPIServer:
    oidcIssuerURL: ${oidc_issuer_url}
    oidcClientID: kubernetes
  kubernetesVersion: ${k8s_version}
  masterInternalName: api.internal.${name}
  masterPublicName: api.${name}
  networkCIDR: ${vpc_cidr}
  networkID: ${vpc_id}
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
${master_subnets}
${worker_subnets}
${utility_subnets}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
${master_instance_group}
${worker_instance_group}
