---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: ${name}
spec:
  api:
    loadBalancer:
      type: Public
      idleTimeoutSeconds: 300
  channel: stable
  cloudProvider: aws
  configBase: s3://${k8s_data_bucket}/${name}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: ${k8s_version}
  masterInternalName: api.internal.kops.k8s-int-kops.skyscrape.rs
  masterPublicName: api.kops.k8s-int-kops.skyscrape.rs
  networkCIDR: ${vpc_cidr}
  networkID: ${vpc_id}
  networking:
    cni: {}
  nonMasqueradeCIDR: 100.65.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
${master_subnets}
${utility_subnets}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
