apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: /etc/kubernetes/pki/ca/ca.pem
      server: http://127.0.0.1:8080
      name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: kubelet
      name: kubelet-to-kubernetes
current-context: kubelet-to-kubernetes
users:
  - name: kubelet
